name: "ivmostr"
project_id: "ivm-ostr-srv"
port: ${PORT}
relay_host: "localhost"
# accepts: public | authenticated | paid 
relay_access: "public"
# defined in milliseconds
ws_io_operation_timeout: 100
# pool's max workers 
pool_max_workers: ${POOL_MAX_WORKERS}
# pool's max tasks per worker
pool_queue: ${POOL_QUEUE}
# Max number of connections from one IP allowed
max_conns_per_ip: 3
# Max number of errors per connection allowed (this is not all errors, but only protocol definition errors)
max_errs_per_conn: 5
trusted_origins:
  - "nostr.ivmanto.dev"
  - "relay.ivmanto.dev"
  - "localhost"
  - "127.0.0.1"
  - "nostr.watch"
  - "nostr.info"
  - "nostr.band"
  - "nostrcheck.me"
  - "flycat.club"
  - "nostr"
cloud_logging_enabled: true
firestore:
  project_id: ${FIRESTORE_PROJECT_ID}
  # set the default value for missing limit value - the max number of events 
  # to be retrurned for the initial query per subscription.
  default_limit: 20
  events_collection_name: "events"
  whitelist_collection_name: "whitelist"
  blacklist_collection_name: "blacklist"
